### ISSUE TITLE
IMKPinching Parameters

### ISSUE THREAD

**Issue by OmidToussi** [amaelkady/Updated-IMK-Models-for-OpenSEES#14]
I am currently working on a research project involving the use of OpenSees software. Specifically, I am focusing on the implementation of material inputs for concentrated plasticity models by using IMKPinching material.
 
In the previous versions of the material model in OpenSees, I remember that we needed to consider the (n+1/n) factor to modify both the initial (Ke) and strain hardening parts of the backbone. As I understand, there have been updates in the software and the method of incorporating this factor might have evolved.
 
Given this, I am reaching out to inquire about the correct procedure or approach in the new version of OpenSees when it comes to using the (n+1/n) factor. Specifically:
 
How should I utilize this factor to modify the initial and hardening strain of the backbone in this updated version or should I use any modification at all?
Are there any specific considerations or adjustments needed when the rotational spring is connected in series with an elastic element for a cantilever RC column?
I am keen to ensure that my implementation is both accurate and consistent with the latest recommendations and guidelines associated with OpenSees. Any insights, references, or documentation that you can provide on this topic would be immensely helpful.
Thank you.
![1](https://github.com/amaelkady/Updated-IMK-Models-for-OpenSEES/assets/148578056/76a0bcb9-f94d-4aca-a35a-6384a02dcec2)

**Comment by amaelkady** [comment]
@OmidToussi The (n+1/n) factor has nothing to do with the material model being used. This factor is used to essentially make the zero-length spring too stiff since the elastic stiffness is already represented by the beam element.

For accuracy, the plastic deformation parameters of the spring can be modified such that the sum of the beam deformation and the spring deformation result in the target/correct response. This has nothing to do with the (n) factor. You can check this example tcl subroutine for how the deformations are modified:

https://github.com/amaelkady/FM-2D/blob/master/src/Spring_IMK.tcl

**Comment by OmidToussi** [comment]
Thanks for your reply and the file you kindly provided.
I have a question about an example you sent.
As you can see in the script you already sent, for calculating theta_pc part, you are adding up the deformations of plastic and yielding points too 
(set theta_pc [expr $theta_pc + $theta_y + ($McMyP-1.0)*$My/(6 * $E * $Ix / $L)])
but in the material model description, $theta_pc is the deformation between capping and ultimate points and not the total deformation. Could you explain this conflict, please?
![inputs](https://github.com/amaelkady/Updated-IMK-Models-for-OpenSEES/assets/148578056/daebf7f3-4794-442b-b902-fdb024942c3c)
![IMK](https://github.com/amaelkady/Updated-IMK-Models-for-OpenSEES/assets/148578056/6146dacb-27cc-452a-8968-82631660898d)

**Comment by amaelkady** [comment]
The script/mathematical formula above adds the elastic rotation components to the "plastic" theta_pc (in this case) and not the total rotations. As mentioned earlier, this is done such that the total deformation of the spring adds up at then end.
