### ISSUE TITLE
Inappropriate Unloading Stiffness in IMK Peak Oriented

### ISSUE THREAD

**Issue by z-ichinohe** [amaelkady/Updated-IMK-Models-for-OpenSEES#3]
Hello Ahmed,

  I'm Kazuki. I think Ei calculation for unloading stiffness deterioration is not correct. 
  A **"plus"** should be **"minus"** between Energy_Diss and 0.5*(fi_1 /  Kul_j_1)*fi_1 in line 246 of IMKPeakOriented.cpp.
  It causes too much stiffness degradation in little plastic rotation and evokes another bug which results in sudden collapse.  I don't know why it evokes sudden collapse but with the modification I encountered much less.
  I already confirmed that it's not compatible with line 303 in ModIMKPeakOriented.cpp.
  I hope you understand that and master codes are soon revised.

**Comment by z-ichinohe** [comment]
These are the relationship between small plastic rotation and its unloading stiffness in one excitation. 
## before
![0622_unloading_stiffness_before](https://user-images.githubusercontent.com/76049354/174990340-02808c78-151c-4abf-9e29-b0b35756f8a6.svg)
## after
![0622_unloading_stiffness_after](https://user-images.githubusercontent.com/76049354/174990346-6a7e57ea-4cae-4b97-9def-9df2d486fbe2.svg)

**Comment by amaelkady** [comment]
Thank you Kazuki for raising the issue.
I will check the code line in question and update it asap if needed. I will keep you posted

**Comment by amaelkady** [comment]
could you also please specify what is the formula in question and what is the proposed modification

**Comment by z-ichinohe** [comment]
When calculating betaK for stiffness deterioration in IMK model, we should subtract elastic energy released by unloading from both EiK and EpjK in my understanding.
"EpjK = Energy_Acc - RSE" is OK but "EiK = Energy_Acc - Energy_Diss + RSE" is incorrect in your script line 245 and 246 where RSE = 0.5(fi_1 / Kul_j_1)* fi_1. It should be "EiK = Energy_Acc - Energy_Diss - RSE" and it is the modification I mentioned.

**Comment by z-ichinohe** [comment]
Thank you so much for your swift correspondence! I already confirmed that the amendment in stiffness deterioration with small deformation works well but also noticed that its deterioration speed is a half of modified one by myself. Is it your intended alteration? 
I have a plan to execute thorough check through incremental dynamic analysis, but it takes time to set up and run. Please wait a moment if you are interested in.

**Comment by amaelkady** [comment]
Yes, the stiffness deteriorates and half the rate of the other mechanisms as discribed in the originial publication by Ibarra.

**Comment by z-ichinohe** [comment]
>Furthermore, this is the only deterioration mode in which the deteriorating quantity, i.e. the unloading stiffness, is updated simultaneously in both directions (i.e. for positive and negative unloading). Consequently, the unloading stiffness deteriorates up to twice as much as the other deteriorating quantities, and if the same rate of deterioration is expected in the four deterioration modes, γk should be about twice as large as the other γ values, i.e. γk = 2γ_s, c, a.

-- Ibarra et al., Hysteretic models that incorporate strength and stiffness deterioration, 2005 p.1497

I think he says unloading stiffness deteriorates two times faster than the other does because there is no distinction between positive one and negative one, which the other deteriorating quantities have. 

First of all, I confirmed that the current deterioration rate is theoretically correct, so there is no problem. Thanks.

**Comment by z-ichinohe** [comment]
OpenSeesPy for Win built with your new code works well and it's satisfying to execute some supplementary analyses, but OpenSeesPy for Mac is desirable for me to execute larger ones. Could you let me know your view on whether will it be merged to the master branch of OpenSees and provided via PyPi or not?

**Comment by amaelkady** [comment]
I will push the updated to OpenSEES master soon after running some robustness checks. It might take a while however for it to be officialy merged. You can always fork and compile your own versions.

**Comment by z-ichinohe** [comment]
Thanks, I got it.
