### ISSUE TITLE
Convergence Problem with negative tangent stiffness

### ISSUE THREAD

**Issue by z-ichinohe** [amaelkady/Updated-IMK-Models-for-OpenSEES#4]
Hello, Ahmed.

 I encountered an convergence problem with your revised code. It works well in one dimensional spring, but it fails in two dimensional members or frames just after its tangent stiffness become negative.
The problem disappears when I replaced "fi_1 >= 0" with "fi_1 > 0". I don't know why it affects its convergence, but it does work.

**Comment by amaelkady** [comment]
thanks for checking.
1. Can you let me know what line code number you are reffering to.
2. Can you send me the spring parameters and the deformation history where you encountered the bug.

**Comment by z-ichinohe** [comment]
1. Line Number 152 in IMKPeakOriented.cpp.
2. I got the problem in a frame analysis, so give me time to specify and minimize reproductive conditions.

**Comment by z-ichinohe** [comment]
This is what happened in one spring and one beam simple system pushover. It's different from the convergence problem I mentioned but it's also caused by that inequality sign difference. I also attached a script file and histories of the spring. 

![0702_imk_member](https://user-images.githubusercontent.com/76049354/176998981-6a047788-9f80-408f-a516-a9d47e53d910.svg)
[zichi.zip](https://github.com/amaelkady/Updated-IMK-Models-for-OpenSEES/files/9032942/zichi.zip)

**Comment by amaelkady** [comment]
Thank you.
The code and exe are updated.

**Comment by z-ichinohe** [comment]
Thank you so much.
